### ISSUE TITLE
[布里斯比羅吉] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#109]
http://www.aoetw.com/batt/Prithviraja

**Comment by bookthief108** [comment]
http://www.aoetw.com/batt/Prithviraj/
WIKI把英雄跟戰役放在同一頁，也許Aoetw也比照辦理
https://ageofempires.fandom.com/wiki/Prithviraj

**Comment by webrsb** [comment]
我覺得還是分兩頁好，一頁是介紹英雄數值，一頁是介紹歷史及他的相關戰役

**Comment by bookthief108** [comment]
剛剛查了英雄頁面跟戰役頁面是分開的
英雄:http://www.aoetw.com/units/hero/Prithviraj/
戰役:http://www.aoetw.com/batt/Prithviraj/
是否將上述戰役的網址更改為http://www.aoetw.com/batt/Prithviraja

**Comment by webrsb** [comment]
英雄單位頁有 `hero` 的路徑可用，因此建議為
```
http://www.aoetw.com/units/hero/Prithviraj/
```

**Comment by webrsb** [comment]
真是怪了，所以這個頁面都寫好了沒有少？因為英雄、戰役頁面都有

**Comment by webrsb** [comment]
已有頁面故關閉
