### ISSUE TITLE
[波斯弓兵] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#303]
http://www.aoetw.com/techs/Kamandaran
英文版wiki: https://ageofempires.fandom.com/wiki/Kamandaran

**Comment by webrsb** [comment]
更新檔34399
Persians
Increased the cost of Archer units after researching the Kamandaran technology from 50 to 60 wood.

**Comment by webrsb** [comment]
更新檔35584
Increased the cost of researching the Kamandaran technology from 200 food, 200 gold to 400 food, 300 gold.

**Comment by singsing612** [comment]
認領

**Comment by webrsb** [comment]
Closed in #308
