### ISSUE TITLE
[韃靼] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#305]
http://www.aoetw.com/civs/Tatars
英文wiki：https://ageofempires.fandom.com/wiki/Tatars

**Comment by webrsb** [comment]
#35584 更新
Now have access to the Halberdier unit.

**Comment by webrsb** [comment]
36202 更新
Now gain the Thumb Ring technology for free as a civilization bonus.
Keshik: Reduced the training time from 23 to 16 seconds.
Elite Keshik: Reduced the training time from 20 to 14 seconds.
Silk Armor: Now grants its benefits to Steppe Lancers.
Timurid Siegecraft: Increased the bonus range granted to Trebuchets from +1 to +2.
Timurid Siegecraft: Now makes the new Flaming Camel unit available when researched—a fast-moving Petard with bonuses vs. mounted units and elephants.

**Comment by singsing612** [comment]
"https://i.imgur.com/lyNDpAZ.jpg"
位於烏茲別克撒馬爾罕的烏魯伯格天文台

**Comment by singsing612** [comment]
"https://i.imgur.com/6xwNXmH.jpg"
韃靼世界奇觀 烏魯伯格天文台

**Comment by singsing612** [comment]
"https://i.imgur.com/0ReU4Qk.jpg"
帖木兒帝國的奠基人 帖木兒
