### ISSUE TITLE
[庫曼] 缺少頁面，待認領 

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#306]
http://www.aoetw.com/civs/Cumans
英文wiki：https://ageofempires.fandom.com/wiki/Cumans

**Comment by webrsb** [comment]
36202 更新
No longer have access to the Redemption technology.
Can now research the Capped Ram upgrade in the Castle Age as a civilization bonus.
Kipchak [Standard & Elite]: Now fire +1 extra arrow.
Steppe Husbandry: Now grants its benefits to Steppe Lancers.
Steppe Husbandry: Now reduces the training time of Scout Cavalry, Cavalry Archers, and Steppe Lancers by 50% (was 80%).

**Comment by singsing612** [comment]
認領

**Comment by singsing612** [comment]
"https://i.imgur.com/usre6L6.jpg"
位於俄羅斯羅斯托夫州的Sarkel要塞

**Comment by singsing612** [comment]
"https://i.imgur.com/vcP7a1Q.jpg"
庫曼世界奇觀 Sarkel要塞
