### ISSUE TITLE
[民兵系相關頁面] 保加利亞的協議特性需更新相關頁面

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#307]
保加利亞研發協議可增加額外防禦，需更新民兵系相關的頁面

**Comment by singsing612** [comment]
新民兵系??是加在協議的頁面上嗎？還是另開頁面?

**Comment by webrsb** [comment]
民兵 http://www.aoetw.com/units/Militia/
裝甲步兵 http://www.aoetw.com/units/Man-at-Arms/
長劍兵 http://www.aoetw.com/units/Long_Swordsman/
劍兵勇士 http://www.aoetw.com/units/Champion/
都屬於民兵系，需要更新相關頁面的章節
1. 更多數據/防禦 表格部份追加
2. 更新日誌/決定版 要追加 「...引入協議...」
3. 如果有數據之外的也可以追加，如 研發協議有什麼戰略上的幫助，可寫在戰術部份

**Comment by singsing612** [comment]
已update

**Comment by webrsb** [comment]
Close in c2e362579e97a460f58d7e886a42cf2c11016fca, 2a9fd572114ccf1212dae1e9820b4384b94f80c4, 4b2a15c30465d2195f72630d7f5eaa6c5aae8ed0, b5e83d718868ff3654484ec102f8755e329c70d1
