### ISSUE TITLE
[保加利亞] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#311]
http://www.aoetw.com/civs/Bulgarians
英文wiki：https://ageofempires.fandom.com/wiki/Bulgarians

**Comment by singsing612** [comment]
認領

**Comment by singsing612** [comment]
文明的首選戰略是憑自己的看法，還是留給高人打進去，因為比較主觀，英文wiki也没提

**Comment by bookthief108** [comment]
可以自己打，或是丟到群組問高手；或是等高手來自己丟攻略我們負責審查就好

**Comment by singsing612** [comment]
"https://i.imgur.com/U1guesG.jpg"
位於保加利亞大普雷斯拉夫的普雷斯拉夫圓頂教堂

**Comment by singsing612** [comment]
"https://i.imgur.com/pQAXO1m.jpg"
保加利亞世界奇觀 普雷斯拉夫圓頂教堂
