### ISSUE TITLE
[堡壘] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#317]
http://www.aoetw.com/building/Krepost
英文wiki：https://ageofempires.fandom.com/wiki/Krepost

**Comment by singsing612** [comment]
認領

**Comment by singsing612** [comment]
"https://i.imgur.com/bQU2lux.png"

**Comment by singsing612** [comment]
要怎樣edit已經PR的file呢?

**Comment by webrsb** [comment]
建議直接開新的，這個 PR 似乎已棄坑
