### ISSUE TITLE
[烈堤司] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#318]
http://www.aoetw.com/units/Leitis
英文wiki：https://ageofempires.fandom.com/wiki/Leitis

**Comment by singsing612** [comment]
圖片要怎麼upload?

**Comment by webrsb** [comment]
圖片先傳 https://imgur.com/
然後對圖片按右鍵取網址，放在 <img src"">的雙引號之中
到時我會再下載回來上傳至網站中

**Comment by singsing612** [comment]
<img src"">的雙引號是什麼?在哪裏?

**Comment by webrsb** [comment]
舉例：<img src="https://i.imgur.com/1dDczmF.jpg">
上傳圖片後，把網址這樣放在裡面就會產生圖片了

**Comment by singsing612** [comment]
"https://i.imgur.com/h9oVVqT.png"

**Comment by singsing612** [comment]
明白了

**Comment by singsing612** [comment]
認領
