### ISSUE TITLE
[欽察] 缺少頁面，待認領

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#319]
http://www.aoetw.com/units/Kipchak
英文wiki：https://ageofempires.fandom.com/wiki/Kipchak

**Comment by singsing612** [comment]
"https://i.imgur.com/g0L5mnH.png"

**Comment by singsing612** [comment]
認領

**Comment by webrsb** [comment]
Closed by 38995d58cb3d0779b2cace3114d4bebb41efc5e1
