### ISSUE TITLE
[烈堤司] 戰術要點章節有部份未翻譯

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#331]
http://www.aoetw.com/units/Leitis
英文wiki：https://ageofempires.fandom.com/wiki/Leitis

Through being a unique unit that can deal high damage against their direct counters, Halberdiers and Camel Riders still pose a threat to them, since they are cost-effective thanks to their high amount of bonus damage against cavalry. Also, they can be defeated by other unique units such as the Samurai, Kamayuk, Genoese Crossbowman, Mameluke and War Elephant, though they will receive a lot of damage from Leitis.

**Comment by singsing612** [comment]
這段主要在説劣勢與優勢兵種，在更多數據中已經寫入，没必要吧?

**Comment by webrsb** [comment]
OK 那這段不要加入，我再刪掉
