### ISSUE TITLE
有關幾個大項目名稱的建議

### ISSUE THREAD

**Issue by harry3305** [webrsb/aoetw#511]
大項目中 遊戲元素的"血量"建議是否能改成"生命點數"或是"耐久值"之類的原意名稱(Hit_points)?
因為血量是比較通俗易懂的說法 但我覺得這種百科全書網還是用正式的名稱比較好  
該項目的"回血"同理也建議改成"自我復原" 寫法也比較正式又一眼就看得出原意

**Comment by webrsb** [comment]
抱歉有點晚才回復，目前的確有在做譯名統一，官方譯名是：生命值 ，因此會朝這個方向去修改，謝謝提醒！
