### ISSUE TITLE
[金礦谷] 圖放了百湖之城

### ISSUE THREAD

**Issue by webrsb** [webrsb/aoetw#53]
* [金礦谷](http://www.aoetw.com/maps/Golden_Pit)
 [關聯討論](http://www.aoetw.com/talk?place=msg%2Faoetw%2FwjjuRAQmB_w%2FnzArq9K4CQAJ)
> 對金礦谷的解說中，圖放了百湖之城，而內文有金礦谷誤寫金礦股 斯堪地納維亞寫成斯堪地維亞

**Comment by webrsb** [comment]
Will fixed via #128

**Comment by bookthief108** [comment]
1080505賜齡認領，問題皆已解決。
